// *** WARNING: this file was generated by crd2pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../../utilities";

// Export members:
export { MCPGClusterArgs } from "./mcpgcluster";
export type MCPGCluster = import("./mcpgcluster").MCPGCluster;
export const MCPGCluster: typeof import("./mcpgcluster").MCPGCluster = null as any;
utilities.lazyLoad(exports, ["MCPGCluster"], () => require("./mcpgcluster"));

export { MCPGClusterListArgs } from "./mcpgclusterList";
export type MCPGClusterList = import("./mcpgclusterList").MCPGClusterList;
export const MCPGClusterList: typeof import("./mcpgclusterList").MCPGClusterList = null as any;
utilities.lazyLoad(exports, ["MCPGClusterList"], () => require("./mcpgclusterList"));

export { MCPGClusterPatchArgs } from "./mcpgclusterPatch";
export type MCPGClusterPatch = import("./mcpgclusterPatch").MCPGClusterPatch;
export const MCPGClusterPatch: typeof import("./mcpgclusterPatch").MCPGClusterPatch = null as any;
utilities.lazyLoad(exports, ["MCPGClusterPatch"], () => require("./mcpgclusterPatch"));

export { MCPGGatewayArgs } from "./mcpggateway";
export type MCPGGateway = import("./mcpggateway").MCPGGateway;
export const MCPGGateway: typeof import("./mcpggateway").MCPGGateway = null as any;
utilities.lazyLoad(exports, ["MCPGGateway"], () => require("./mcpggateway"));

export { MCPGGatewayListArgs } from "./mcpggatewayList";
export type MCPGGatewayList = import("./mcpggatewayList").MCPGGatewayList;
export const MCPGGatewayList: typeof import("./mcpggatewayList").MCPGGatewayList = null as any;
utilities.lazyLoad(exports, ["MCPGGatewayList"], () => require("./mcpggatewayList"));

export { MCPGGatewayPatchArgs } from "./mcpggatewayPatch";
export type MCPGGatewayPatch = import("./mcpggatewayPatch").MCPGGatewayPatch;
export const MCPGGatewayPatch: typeof import("./mcpggatewayPatch").MCPGGatewayPatch = null as any;
utilities.lazyLoad(exports, ["MCPGGatewayPatch"], () => require("./mcpggatewayPatch"));

export { MCPGPluginArgs } from "./mcpgplugin";
export type MCPGPlugin = import("./mcpgplugin").MCPGPlugin;
export const MCPGPlugin: typeof import("./mcpgplugin").MCPGPlugin = null as any;
utilities.lazyLoad(exports, ["MCPGPlugin"], () => require("./mcpgplugin"));

export { MCPGPluginListArgs } from "./mcpgpluginList";
export type MCPGPluginList = import("./mcpgpluginList").MCPGPluginList;
export const MCPGPluginList: typeof import("./mcpgpluginList").MCPGPluginList = null as any;
utilities.lazyLoad(exports, ["MCPGPluginList"], () => require("./mcpgpluginList"));

export { MCPGPluginMirrorArgs } from "./mcpgpluginMirror";
export type MCPGPluginMirror = import("./mcpgpluginMirror").MCPGPluginMirror;
export const MCPGPluginMirror: typeof import("./mcpgpluginMirror").MCPGPluginMirror = null as any;
utilities.lazyLoad(exports, ["MCPGPluginMirror"], () => require("./mcpgpluginMirror"));

export { MCPGPluginMirrorListArgs } from "./mcpgpluginMirrorList";
export type MCPGPluginMirrorList = import("./mcpgpluginMirrorList").MCPGPluginMirrorList;
export const MCPGPluginMirrorList: typeof import("./mcpgpluginMirrorList").MCPGPluginMirrorList = null as any;
utilities.lazyLoad(exports, ["MCPGPluginMirrorList"], () => require("./mcpgpluginMirrorList"));

export { MCPGPluginMirrorPatchArgs } from "./mcpgpluginMirrorPatch";
export type MCPGPluginMirrorPatch = import("./mcpgpluginMirrorPatch").MCPGPluginMirrorPatch;
export const MCPGPluginMirrorPatch: typeof import("./mcpgpluginMirrorPatch").MCPGPluginMirrorPatch = null as any;
utilities.lazyLoad(exports, ["MCPGPluginMirrorPatch"], () => require("./mcpgpluginMirrorPatch"));

export { MCPGPluginPatchArgs } from "./mcpgpluginPatch";
export type MCPGPluginPatch = import("./mcpgpluginPatch").MCPGPluginPatch;
export const MCPGPluginPatch: typeof import("./mcpgpluginPatch").MCPGPluginPatch = null as any;
utilities.lazyLoad(exports, ["MCPGPluginPatch"], () => require("./mcpgpluginPatch"));

export { MCPGPluginSetArgs } from "./mcpgpluginSet";
export type MCPGPluginSet = import("./mcpgpluginSet").MCPGPluginSet;
export const MCPGPluginSet: typeof import("./mcpgpluginSet").MCPGPluginSet = null as any;
utilities.lazyLoad(exports, ["MCPGPluginSet"], () => require("./mcpgpluginSet"));

export { MCPGPluginSetListArgs } from "./mcpgpluginSetList";
export type MCPGPluginSetList = import("./mcpgpluginSetList").MCPGPluginSetList;
export const MCPGPluginSetList: typeof import("./mcpgpluginSetList").MCPGPluginSetList = null as any;
utilities.lazyLoad(exports, ["MCPGPluginSetList"], () => require("./mcpgpluginSetList"));

export { MCPGPluginSetPatchArgs } from "./mcpgpluginSetPatch";
export type MCPGPluginSetPatch = import("./mcpgpluginSetPatch").MCPGPluginSetPatch;
export const MCPGPluginSetPatch: typeof import("./mcpgpluginSetPatch").MCPGPluginSetPatch = null as any;
utilities.lazyLoad(exports, ["MCPGPluginSetPatch"], () => require("./mcpgpluginSetPatch"));

export { MCPGRevocationListArgs } from "./mcpgrevocationList";
export type MCPGRevocationList = import("./mcpgrevocationList").MCPGRevocationList;
export const MCPGRevocationList: typeof import("./mcpgrevocationList").MCPGRevocationList = null as any;
utilities.lazyLoad(exports, ["MCPGRevocationList"], () => require("./mcpgrevocationList"));

export { MCPGRevocationListListArgs } from "./mcpgrevocationListList";
export type MCPGRevocationListList = import("./mcpgrevocationListList").MCPGRevocationListList;
export const MCPGRevocationListList: typeof import("./mcpgrevocationListList").MCPGRevocationListList = null as any;
utilities.lazyLoad(exports, ["MCPGRevocationListList"], () => require("./mcpgrevocationListList"));

export { MCPGRevocationListPatchArgs } from "./mcpgrevocationListPatch";
export type MCPGRevocationListPatch = import("./mcpgrevocationListPatch").MCPGRevocationListPatch;
export const MCPGRevocationListPatch: typeof import("./mcpgrevocationListPatch").MCPGRevocationListPatch = null as any;
utilities.lazyLoad(exports, ["MCPGRevocationListPatch"], () => require("./mcpgrevocationListPatch"));

export { MCPGRouteArgs } from "./mcpgroute";
export type MCPGRoute = import("./mcpgroute").MCPGRoute;
export const MCPGRoute: typeof import("./mcpgroute").MCPGRoute = null as any;
utilities.lazyLoad(exports, ["MCPGRoute"], () => require("./mcpgroute"));

export { MCPGRouteListArgs } from "./mcpgrouteList";
export type MCPGRouteList = import("./mcpgrouteList").MCPGRouteList;
export const MCPGRouteList: typeof import("./mcpgrouteList").MCPGRouteList = null as any;
utilities.lazyLoad(exports, ["MCPGRouteList"], () => require("./mcpgrouteList"));

export { MCPGRoutePatchArgs } from "./mcpgroutePatch";
export type MCPGRoutePatch = import("./mcpgroutePatch").MCPGRoutePatch;
export const MCPGRoutePatch: typeof import("./mcpgroutePatch").MCPGRoutePatch = null as any;
utilities.lazyLoad(exports, ["MCPGRoutePatch"], () => require("./mcpgroutePatch"));

export { MCPGTenantArgs } from "./mcpgtenant";
export type MCPGTenant = import("./mcpgtenant").MCPGTenant;
export const MCPGTenant: typeof import("./mcpgtenant").MCPGTenant = null as any;
utilities.lazyLoad(exports, ["MCPGTenant"], () => require("./mcpgtenant"));

export { MCPGTenantListArgs } from "./mcpgtenantList";
export type MCPGTenantList = import("./mcpgtenantList").MCPGTenantList;
export const MCPGTenantList: typeof import("./mcpgtenantList").MCPGTenantList = null as any;
utilities.lazyLoad(exports, ["MCPGTenantList"], () => require("./mcpgtenantList"));

export { MCPGTenantPatchArgs } from "./mcpgtenantPatch";
export type MCPGTenantPatch = import("./mcpgtenantPatch").MCPGTenantPatch;
export const MCPGTenantPatch: typeof import("./mcpgtenantPatch").MCPGTenantPatch = null as any;
utilities.lazyLoad(exports, ["MCPGTenantPatch"], () => require("./mcpgtenantPatch"));


const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "kubernetes:mcpg.dev/v1alpha1:MCPGCluster":
                return new MCPGCluster(name, <any>undefined, { urn })
            case "kubernetes:mcpg.dev/v1alpha1:MCPGClusterList":
                return new MCPGClusterList(name, <any>undefined, { urn })
            case "kubernetes:mcpg.dev/v1alpha1:MCPGClusterPatch":
                return new MCPGClusterPatch(name, <any>undefined, { urn })
            case "kubernetes:mcpg.dev/v1alpha1:MCPGGateway":
                return new MCPGGateway(name, <any>undefined, { urn })
            case "kubernetes:mcpg.dev/v1alpha1:MCPGGatewayList":
                return new MCPGGatewayList(name, <any>undefined, { urn })
            case "kubernetes:mcpg.dev/v1alpha1:MCPGGatewayPatch":
                return new MCPGGatewayPatch(name, <any>undefined, { urn })
            case "kubernetes:mcpg.dev/v1alpha1:MCPGPlugin":
                return new MCPGPlugin(name, <any>undefined, { urn })
            case "kubernetes:mcpg.dev/v1alpha1:MCPGPluginList":
                return new MCPGPluginList(name, <any>undefined, { urn })
            case "kubernetes:mcpg.dev/v1alpha1:MCPGPluginMirror":
                return new MCPGPluginMirror(name, <any>undefined, { urn })
            case "kubernetes:mcpg.dev/v1alpha1:MCPGPluginMirrorList":
                return new MCPGPluginMirrorList(name, <any>undefined, { urn })
            case "kubernetes:mcpg.dev/v1alpha1:MCPGPluginMirrorPatch":
                return new MCPGPluginMirrorPatch(name, <any>undefined, { urn })
            case "kubernetes:mcpg.dev/v1alpha1:MCPGPluginPatch":
                return new MCPGPluginPatch(name, <any>undefined, { urn })
            case "kubernetes:mcpg.dev/v1alpha1:MCPGPluginSet":
                return new MCPGPluginSet(name, <any>undefined, { urn })
            case "kubernetes:mcpg.dev/v1alpha1:MCPGPluginSetList":
                return new MCPGPluginSetList(name, <any>undefined, { urn })
            case "kubernetes:mcpg.dev/v1alpha1:MCPGPluginSetPatch":
                return new MCPGPluginSetPatch(name, <any>undefined, { urn })
            case "kubernetes:mcpg.dev/v1alpha1:MCPGRevocationList":
                return new MCPGRevocationList(name, <any>undefined, { urn })
            case "kubernetes:mcpg.dev/v1alpha1:MCPGRevocationListList":
                return new MCPGRevocationListList(name, <any>undefined, { urn })
            case "kubernetes:mcpg.dev/v1alpha1:MCPGRevocationListPatch":
                return new MCPGRevocationListPatch(name, <any>undefined, { urn })
            case "kubernetes:mcpg.dev/v1alpha1:MCPGRoute":
                return new MCPGRoute(name, <any>undefined, { urn })
            case "kubernetes:mcpg.dev/v1alpha1:MCPGRouteList":
                return new MCPGRouteList(name, <any>undefined, { urn })
            case "kubernetes:mcpg.dev/v1alpha1:MCPGRoutePatch":
                return new MCPGRoutePatch(name, <any>undefined, { urn })
            case "kubernetes:mcpg.dev/v1alpha1:MCPGTenant":
                return new MCPGTenant(name, <any>undefined, { urn })
            case "kubernetes:mcpg.dev/v1alpha1:MCPGTenantList":
                return new MCPGTenantList(name, <any>undefined, { urn })
            case "kubernetes:mcpg.dev/v1alpha1:MCPGTenantPatch":
                return new MCPGTenantPatch(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("mcpg", "mcpg.dev/v1alpha1", _module)
